name: CI Quality Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.3-eclipse-temurin-17

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Compilar proyecto
        run: mvn -B clean install

      - name: Ejecutar Checkstyle
        run: mvn checkstyle:check

      - name: Ejecutar pruebas y generar cobertura
        run: mvn -B verify

      - name: Mostrar reporte de cobertura
        if: always()
        run: |
          echo "El reporte HTML está en target/site/jacoco/index.html"
          echo "El XML está en target/site/jacoco/jacoco.xml"
